FROM registry.redhat.io/ubi9/python-312-minimal@sha256:ba0413d56e6ecfa5dda5996f1b797e3b2e7cc798849fb97d4c75c1cfd721f4de AS builder

WORKDIR /app
COPY src /app/src
COPY pyproject.toml /app/
COPY README.md /app/
COPY LICENSE /app/
RUN pip install .

FROM registry.redhat.io/ubi9/python-312-minimal@sha256:ba0413d56e6ecfa5dda5996f1b797e3b2e7cc798849fb97d4c75c1cfd721f4de

COPY --from=builder /opt/app-root/bin /opt/app-root/bin
COPY --from=builder /opt/app-root/lib64/python3.12/site-packages /opt/app-root/lib64/python3.12/site-packages
COPY LICENSE /licenses/license.txt

USER 65532:65532

ENTRYPOINT ["model_signing"]
CMD ["--help"]

LABEL description="Supply chain security for ML"
LABEL io.k8s.description="Supply chain security for ML"
LABEL io.k8s.display-name="Model Transparency Library"
LABEL io.openshift.tags="model transparency security ml"
LABEL summary="Provides a library for model transparency."
LABEL com.redhat.component="model-transparency"
LABEL name="rhtas/model-transparency-rhel9"
