apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/securesign/model-transparency?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: model-transparency
    appstudio.openshift.io/component: model-transparency
    pipelines.appstudio.openshift.io/type: build
  name: model-transparency-on-push
  namespace: rhtas-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/securesign/model-transparency:{{revision}}
  - name: dockerfile
    value: Dockerfile.model-transparency.rh
  - name: path-context
    value: .
  - name: build-source-image
    value: "true"
  - name: build-platforms
    value:
      - linux/x86_64
      - linux/arm64
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: 'https://github.com/securesign/pipelines.git'
      - name: revision
        value: 'main'
      - name: pathInRepo
        value: 'pipelines/docker-build-multi-platform-oci-ta.yaml'
  taskRunTemplate:
    serviceAccountName: build-pipeline-model-transparency
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
